FROM prom/prometheus:latest

COPY prometheus.yml /etc/prometheus/
COPY rules /etc/prometheus/rules

EXPOSE 9090

CMD ["--config.file=/etc/prometheus/prometheus.yml", \
     "--storage.tsdb.path=/prometheus", \
     "--web.console.libraries=/usr/share/prometheus/console_libraries", \
     "--web.console.templates=/usr/share/prometheus/consoles"]
